### ISSUE TITLE
run bash run.sh  error

### ISSUE THREAD

**Issue by Damon2019** [foolwood/SiamMask#114]
when i run bash run.sh
Traceback (most recent call last):
  File "/home/huangf/github/SiamMask/tools/train_siammask.py", line 292, in <module>
    main()
  File "/home/huangf/github/SiamMask/tools/train_siammask.py", line 127, in main
    logger.info("\n" + collect_env_info())
  File "/home/huangf/github/SiamMask/tools/train_siammask.py", line 70, in collect_env_info
    env_str = get_pretty_env_info()
  File "/home/huangf/.conda/envs/siammask/lib/python3.6/site-packages/torch/utils/collect_env.py", line 338, in get_pretty_env_info
    return pretty_str(get_env_info())
  File "/home/huangf/.conda/envs/siammask/lib/python3.6/site-packages/torch/utils/collect_env.py", line 236, in get_env_info
    os=get_os(run_lambda),
  File "/home/huangf/.conda/envs/siammask/lib/python3.6/site-packages/torch/utils/collect_env.py", line 174, in get_os
    desc = get_lsb_version(run_lambda)
  File "/home/huangf/.conda/envs/siammask/lib/python3.6/site-packages/torch/utils/collect_env.py", line 152, in get_lsb_version
    return run_and_parse_first_match(run_lambda, 'lsb_release -a', r'Description:\t(.*)')
  File "/home/huangf/.conda/envs/siammask/lib/python3.6/site-packages/torch/utils/collect_env.py", line 57, in run_and_parse_first_match
    rc, out, _ = run_lambda(command)
  File "/home/huangf/.conda/envs/siammask/lib/python3.6/site-packages/torch/utils/collect_env.py", line 43, in run
    err = err.decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 22: ordinal not in range(128)

**Comment by ggy112** [comment]
您好，我想请教以下关于siammask的训练，您是怎么成功训练自己的数据集的

**Comment by huangpan2507** [comment]
> 
> 
> when i run bash run.sh
> Traceback (most recent call last):
> File "/home/huangf/github/SiamMask/tools/train_siammask.py", line 292, in
> main()
> File "/home/huangf/github/SiamMask/tools/train_siammask.py", line 127, in main
> logger.info("\n" + collect_env_info())
> File "/home/huangf/github/SiamMask/tools/train_siammask.py", line 70, in collect_env_info
> env_str = get_pretty_env_info()
> File "/home/huangf/.conda/envs/siammask/lib/python3.6/site-packages/torch/utils/collect_env.py", line 338, in get_pretty_env_info
> return pretty_str(get_env_info())
> File "/home/huangf/.conda/envs/siammask/lib/python3.6/site-packages/torch/utils/collect_env.py", line 236, in get_env_info
> os=get_os(run_lambda),
> File "/home/huangf/.conda/envs/siammask/lib/python3.6/site-packages/torch/utils/collect_env.py", line 174, in get_os
> desc = get_lsb_version(run_lambda)
> File "/home/huangf/.conda/envs/siammask/lib/python3.6/site-packages/torch/utils/collect_env.py", line 152, in get_lsb_version
> return run_and_parse_first_match(run_lambda, 'lsb_release -a', r'Description:\t(.*)')
> File "/home/huangf/.conda/envs/siammask/lib/python3.6/site-packages/torch/utils/collect_env.py", line 57, in run_and_parse_first_match
> rc, out, _ = run_lambda(command)
> File "/home/huangf/.conda/envs/siammask/lib/python3.6/site-packages/torch/utils/collect_env.py", line 43, in run
> err = err.decode("ascii")
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 22: ordinal not in range(128)

how do u solve that problem ?!    I have meet the similar problem like this below：
>File "/home/huangpan/git_download/SiamMask/SiamMask-master/data/trackdat/scripts/unzip_vot.py", line 41, in <module>
    main()
  File "/home/huangpan/git_download/SiamMask/SiamMask-master/data/trackdat/scripts/unzip_vot.py", line 18, in main
    dataset = json.load(f)
  File "/home/huangpan/anaconda3/envs/siammask/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/home/huangpan/anaconda3/envs/siammask/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 264: invalid start byte
Traceback (most recent call last):
  File "/home/huangpan/git_download/SiamMask/SiamMask-master/data/trackdat/scripts/unzip_vot.py", line 41, in <module>
    main()
  File "/home/huangpan/git_download/SiamMask/SiamMask-master/data/trackdat/scripts/unzip_vot.py", line 18, in main
    dataset = json.load(f)
  File "/home/huangpan/anaconda3/envs/siammask/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/home/huangpan/anaconda3/envs/siammask/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 264: invalid start byte
