### ISSUE TITLE
get_test_data.sh

### ISSUE THREAD

**Issue by petit-ami** [foolwood/SiamMask#12]
(siammask) [liqiang@inspur trackdat]$ VOT_YEAR=2016 bash scripts/download_vot.sh dl/vot2016
--2019-03-14 16:18:38--  http://data.votchallenge.net/vot2016/main/description.json
Resolving data.votchallenge.net (data.votchallenge.net)... 194.249.1.179
Connecting to data.votchallenge.net (data.votchallenge.net)|194.249.1.179|:80... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

scripts/download_vot.sh: line 19: jq: command not found
scripts/download_vot.sh: line 20: jq: command not found
scripts/download_vot.sh: line 21: jq: command not found

@foolwood  where is this problem come from? anybody please help me to locate it

**Comment by czla** [comment]
You should install `jq` first.
You can try `sudo apt-get install jq`, it works for me on Ubuntu 16.04.

**Comment by petit-ami** [comment]
thank you for your instruction, but when I run demo,another error come out, can you tell me how ot fix it ?
(siammask) [liqiang@inspur siammask]$ python ../../tools/demo.py --resume SiamMask_DAVIS.pth --config config_davis.json
[2019-03-15 11:03:58,220-rk0-load_helper.py# 31] load pretrained model from SiamMask_DAVIS.pth
[2019-03-15 11:04:01,525-rk0-load_helper.py# 25] remove prefix 'module.'
[2019-03-15 11:04:01,527-rk0-load_helper.py# 18] used keys:356
QObject::moveToThread: Current thread (0x5619f6b19670) is not the object's thread (0x5619f652de70).
Cannot move to target thread (0x5619f6b19670)

QObject::moveToThread: Current thread (0x5619f6b19670) is not the object's thread (0x5619f652de70).
Cannot move to target thread (0x5619f6b19670)

QPixmap: Must construct a QApplication before a QPaintDevice
Aborted (core dumped)
@czla

**Comment by czla** [comment]
sorry, i didn't meet this error, maybe it comes with environment configuration. 
I just run the demo and download the model successfully , haven't tested on these datasets yet.

**Comment by petit-ami** [comment]
@czla @foolwood Thank you for your reply whatever. 
I think it's problem about pyqt, but I dont know how to set up it correctly

**Comment by huangpan2507** [comment]
I have run demo part success。 Then  I follow these step below:

>cd $SiamMask/data
>sudo apt-get install jq
>bash get_test_data.sh

But when I run bash get_test_data.sh, something goes wrong . Then I open the get_test_data.sh
and run the command step by step.
it goes like this:
>
....download success. 200K
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10
parse error: Invalid numeric literal at line 1, column 10

**Comment by huangpan2507** [comment]
who can help me?  I meet this problem below:

>File "/home/huangpan/git_download/SiamMask/SiamMask-master/data/trackdat/scripts/unzip_vot.py", line 41, in <module>
    main()
  File "/home/huangpan/git_download/SiamMask/SiamMask-master/data/trackdat/scripts/unzip_vot.py", line 18, in main
    dataset = json.load(f)
  File "/home/huangpan/anaconda3/envs/siammask/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/home/huangpan/anaconda3/envs/siammask/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 264: invalid start byte
Traceback (most recent call last):
  File "/home/huangpan/git_download/SiamMask/SiamMask-master/data/trackdat/scripts/unzip_vot.py", line 41, in <module>
    main()
  File "/home/huangpan/git_download/SiamMask/SiamMask-master/data/trackdat/scripts/unzip_vot.py", line 18, in main
    dataset = json.load(f)
  File "/home/huangpan/anaconda3/envs/siammask/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/home/huangpan/anaconda3/envs/siammask/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb6 in position 264: invalid start byte
