### ISSUE TITLE
KeyError: 'gt'

### ISSUE THREAD

**Issue by skh0619** [foolwood/SiamMask#123]
When I test with test.py like below,
(conda_activate )G:\SiamMask-master_direct\SiamMask-master\experiments\siammask_sharp>python G:\SiamMask-master_direct\SiamMask-master\tools\test.py --config config_davis.json --resume SiamMask_DAVIS.pth --dataset DAVIS

I got 'gt' error.

[2019-11-21 17:29:03,750-rk0-test.py#555] Namespace(arch='Custom', config='config_davis.json', cpu=False, dataset='DAVIS', debug=False, gt=False, log='log_test.txt', mask=False, refine=False, resume='SiamMask_DAVIS.pth', save_mask=False, video='', visualization=False)
[2019-11-21 17:29:04,194-rk0-features.py# 66] Current training 0 layers:

[2019-11-21 17:29:04,195-rk0-features.py# 66] Current training 1 layers:

[2019-11-21 17:29:04,269-rk0-load_helper.py# 31] load pretrained model from SiamMask_DAVIS.pth
[2019-11-21 17:29:06,370-rk0-load_helper.py# 25] remove prefix 'module.'
[2019-11-21 17:29:06,372-rk0-load_helper.py# 18] used keys:356
Traceback (most recent call last):
  File "G:\SiamMask-master_direct\SiamMask-master\tools\test.py", line 608, in <module>
    main()
  File "G:\SiamMask-master_direct\SiamMask-master\tools\test.py", line 593, in main
    args.mask, args.refine, device=device)
  File "G:\SiamMask-master_direct\SiamMask-master\tools\test.py", line 320, in track_vot
    image_files, gt = video['image_files'], video['gt']
KeyError: 'gt'

Actually I had successfully demo.py 
Plz help me to solve this issue.

**Comment by shupingbaba** [comment]
I also encountered the same problem, did you solve it .
