### ISSUE TITLE
AttributeError: 'Custom' object has no attribute 'track_refine'

### ISSUE THREAD

**Issue by VegetableChlcken** [foolwood/SiamMask#124]
AttributeError: 'Custom' object has no attribute 'track_refine'

How can I do?

**Comment by VegetableChlcken** [comment]
sorry ,My expression is not clear.
when I run python ../../tools/demo.py --resume SiamMask_DAVIS.pth --config config_davis.json
or bash test_mask_refine.sh config_vot.json SiamMask_DAVIS.pth VOT2018 0

The error will appear,But I find Custom have this attribute in the code and I don't change anything in the download code. what's wrong with it and how can I deal with it?

**Comment by VegetableChlcken** [comment]
bash test_mask_refine.sh config_vot.json SiamMask_VOT.pth VOT2018 0
path is: /home/czy/Documents/network/tracking/SiamMask/SiamMask-master
[2019-11-25 12:24:20,767-rk0-test.py#555] Namespace(arch='Custom', config='config_vot.json', cpu=False, dataset='VOT2018', debug=False, gt=False, log='log_test.txt', mask=True, refine=True, resume='SiamMask_VOT.pth', save_mask=False, video='', visualization=False)
[2019-11-25 12:24:20,980-rk0-features.py# 66] Current training 0 layers:
	
[2019-11-25 12:24:20,981-rk0-features.py# 66] Current training 1 layers:
	
[2019-11-25 12:24:21,010-rk0-load_helper.py# 31] load pretrained model from SiamMask_VOT.pth
[2019-11-25 12:24:22,661-rk0-load_helper.py# 25] remove prefix 'module.'
[2019-11-25 12:24:22,662-rk0-load_helper.py# 16] [Warning] unused_pretrained_keys: {'refine_model.post2.weight', 'refine_model.v1.0.weight', 'refine_model.v0.2.weight', 'refine_model.h2.0.weight', 'refine_model.v1.2.weight', 'refine_model.post1.weight', 'refine_model.v1.2.bias', 'refine_model.h1.0.bias', 'refine_model.v0.0.bias', 'refine_model.h0.0.weight', 'refine_model.v2.2.weight', 'refine_model.post0.weight', 'refine_model.h2.2.weight', 'refine_model.h0.2.weight', 'refine_model.post1.bias', 'refine_model.h2.0.bias', 'refine_model.deconv.bias', 'refine_model.deconv.weight', 'refine_model.v1.0.bias', 'refine_model.h0.2.bias', 'refine_model.v0.0.weight', 'refine_model.v2.2.bias', 'refine_model.v0.2.bias', 'refine_model.v2.0.weight', 'refine_model.h1.2.bias', 'refine_model.h1.2.weight', 'refine_model.h2.2.bias', 'refine_model.post2.bias', 'refine_model.h0.0.bias', 'refine_model.post0.bias', 'refine_model.h1.0.weight', 'refine_model.v2.0.bias'}
[2019-11-25 12:24:22,662-rk0-load_helper.py# 17] unused checkpoint keys:32
[2019-11-25 12:24:22,662-rk0-load_helper.py# 18] used keys:324
[2019-11-25 12:24:22,883-rk0-resnet.py<forward>#231] p3 torch.Size([1, 1024, 15, 15])
[2019-11-25 12:24:22,896-rk0-resnet.py<forward>#231] p3 torch.Size([1, 1024, 31, 31])
Traceback (most recent call last):
  File "/home/czy/Documents/network/tracking/SiamMask/SiamMask-master/tools/test.py", line 608, in <module>
    main()
  File "/home/czy/Documents/network/tracking/SiamMask/SiamMask-master/tools/test.py", line 593, in main
    args.mask, args.refine, device=device)
  File "/home/czy/Documents/network/tracking/SiamMask/SiamMask-master/tools/test.py", line 335, in track_vot
    state = siamese_track(state, im, mask_enable, refine_enable, device, args.debug)  # track
  File "/home/czy/Documents/network/tracking/SiamMask/SiamMask-master/tools/test.py", line 257, in siamese_track
    mask = net.track_refine((delta_y, delta_x)).to(device).sigmoid().squeeze().view(
  File "/home/czy/Downloads/yes/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 518, in __getattr__
    type(self).__name__, name))

This is the whole result

**Comment by ks322181** [comment]
i too have the same error.

**Comment by guangqianqin** [comment]
the document who import custom is  /experiments/siammak_base or siammask_sharp
