### ISSUE TITLE
Evaluate performance on VOT

### ISSUE THREAD

**Issue by awethaileslassie** [foolwood/SiamMask#143]
Hello,
I really liked you paper and i am interested in doing some experiments on the code you provided.
but I have faced a problem while doing the evaluation:

python ../../tools/eval.py --dataset VOT2016 --tracker_prefix C --result_dir ./test/VOT2016
loading VOT2016: 100%|█████████████████████████████████████| 60/60 [00:00<00:00, 2127.27it/s, wiper]
eval ar: 100%|████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.65it/s]
eval eao:   0%|                                                               | 0/2 [00:00<?, ?it/s]Exception in thread Thread-8:
Traceback (most recent call last):
  File "/home/msi_awet/anaconda3/envs/siammask/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/msi_awet/anaconda3/envs/siammask/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/msi_awet/anaconda3/envs/siammask/lib/python3.6/multiprocessing/pool.py", line 463, in _handle_results
    task = get()
  File "/home/msi_awet/anaconda3/envs/siammask/lib/python3.6/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'loc'
 

Can you please explain to me how to fix this?
Thank you in advance?

**Comment by wencheng256** [comment]
install numba==0.47.0 would fix this

**Comment by wencheng256** [comment]
@foolwood  Maybe you should update requirements.txt? thanks

**Comment by awethaileslassie** [comment]
Thank you now it is working.

**Comment by haishibei** [comment]
@awethaileslassie hello, how about your testing result on VOT?
