### ISSUE TITLE
Can this project work with CPU？

### ISSUE THREAD

**Issue by zangzelin** [foolwood/SiamMask#15]
As the title, sir.

**Comment by nigyiii** [comment]
I also have the same question.I tried to run demo.py on MacBook without GPUs and `torch.cuda.is_available()` returns `False`, then I got this error

> [2019-03-27 14:43:12,130-rk0-load_helper.py# 31] load pretrained model from SiamMask_DAVIS.pth
Traceback (most recent call last):
  File "../../tools/demo.py", line 29, in <module>
    siammask = load_pretrain(siammask, args.resume)
  File "/Users/ngy/SiamMask/utils/load_helper.py", line 32, in load_pretrain
    device = torch.cuda.current_device()
  File "/Users/ngy/anaconda2/envs/siammask/lib/python3.6/site-packages/torch/cuda/__init__.py", line 341, in current_device
    _lazy_init()
  File "/Users/ngy/anaconda2/envs/siammask/lib/python3.6/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    _check_driver()
  File "/Users/ngy/anaconda2/envs/siammask/lib/python3.6/site-packages/torch/cuda/__init__.py", line 75, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

It seems this is because I installed PyTorch without cuda (my device has no Nvidia gpu). I noticed that in demo.py, line 20, `device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')`
seems device is cpu if `torch.cuda.is_available()` returns `False`
 
So can this project run with PyTorch cpu only, without cuda support?

**Comment by nigyiii** [comment]
I run the demo with cpu only.

In /utils/loader_helper.py, line 32 and 33, change
```
device = torch.cuda.current_device()
pretrained_dict = torch.load(pretrained_path, map_location=lambda storage, loc: storage.cuda(device))
```
into
```
device = torch.device('cpu')
pretrained_dict = torch.load(pretrained_path, map_location='cpu')
```

In /tools/test.py, remove all `.cuda()` in the file

**Comment by linhtn** [comment]
@nigyiii: Thank for your instructions! It works well!

**Comment by zkl99999** [comment]
thank you all, i always think ,train model on gpu,cannot predict on cpu device, i am wrong.

**Comment by RafaelRViana** [comment]
What's the performance (FPS) running on your Macbook's CPU?

**Comment by nigyiii** [comment]
> What's the performance (FPS) running on your Macbook's CPU?

very slow, about 1 fps
