### ISSUE TITLE
The bug in running demo

### ISSUE THREAD

**Issue by Kuangjf2020** [foolwood/SiamMask#170]
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
Traceback (most recent call last):
  File "/home/jfkuang/SiamMask/tools/demo.py", line 53, in <module>
    state = siamese_init(im, target_pos, target_sz, siammask, cfg['hp'], device=device)  # init tracker
  File "/home/jfkuang/SiamMask/tools/test.py", line 155, in siamese_init
    net.template(z.to(device))
  File "/home/jfkuang/SiamMask/experiments/siammask_sharp/custom.py", line 174, in template
    self.zf = self.features(template)
  File "/home/jfkuang/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jfkuang/SiamMask/experiments/siammask_sharp/custom.py", line 59, in forward
    output = self.features(x)
  File "/home/jfkuang/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jfkuang/SiamMask/experiments/siammask_sharp/resnet.py", line 220, in forward
    x = self.conv1(x)
  File "/home/jfkuang/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jfkuang/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:663

**Comment by edgexspear** [comment]
I meet the same error .Have you solved it?

**Comment by edgexspear** [comment]
> THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
> Traceback (most recent call last):
> File "/home/jfkuang/SiamMask/tools/demo.py", line 53, in
> state = siamese_init(im, target_pos, target_sz, siammask, cfg['hp'], device=device) # init tracker
> File "/home/jfkuang/SiamMask/tools/test.py", line 155, in siamese_init
> net.template(z.to(device))
> File "/home/jfkuang/SiamMask/experiments/siammask_sharp/custom.py", line 174, in template
> self.zf = self.features(template)
> File "/home/jfkuang/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/jfkuang/SiamMask/experiments/siammask_sharp/custom.py", line 59, in forward
> output = self.features(x)
> File "/home/jfkuang/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/jfkuang/SiamMask/experiments/siammask_sharp/resnet.py", line 220, in forward
> x = self.conv1(x)
> File "/home/jfkuang/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/jfkuang/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
> self.padding, self.dilation, self.groups)
> RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:663

I meet the same error .Have you solved it?

**Comment by shupingbaba** [comment]
Annotate torch.backends.cudnn.benchmark = True
