### ISSUE TITLE
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp:663

### ISSUE THREAD

**Issue by honda12345** [foolwood/SiamMask#171]
I want to train, but I get this error,
> PyTorch version: 0.4.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176
OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect
Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2070
Nvidia driver version: 450.57
cuDNN version: Could not collect
Versions of relevant libraries:
[pip] Could not collect
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.1           py36_py35_py27__9.0.176_7.1.2_2    pytorch
[conda] torch                     0.4.1                    pypi_0    pypi
[conda] torchvision               0.2.1                    pypi_0    pypi
        OpenCV (3.4.3)
[2020-10-04 05:58:21,487-rk0-train_siammask.py#128] Namespace(arch='', batch=64, clip=10.0, config='config.json', epochs=20, log='logs/log.txt', log_dir='board', lr=0.001, momentum=0.9, pretrained='', print_freq=10, resume='', save_dir='snapshot', start_epoch=0, weight_decay=0.0001, workers=20)
[2020-10-04 05:58:21,487-rk0-train_siammask.py#131] config 
{
    "network": {
        "arch": "Custom"
    },
    "hp": {
        "instance_size": 255,
        "base_size": 8
    },
    "lr": {
        "feature_lr_mult": 1.0,
        "rpn_lr_mult": 1.0,
        "mask_lr_mult": 1.0,
        "type": "log",
        "start_lr": 0.005,
        "end_lr": 0.0025,
        "warmup": {
            "start_lr": 0.001,
            "end_lr": 0.005,
            "type": "step",
            "step": 1,
            "epoch": 5
        }
    },
    "loss": {
        "weight": [
            1.0,
            1.2,
            36
        ],
        "reg": {
            "loss": "L1Loss"
        },
        "cls": {
            "split": true
        }
    },
    "train_datasets": {
        "datasets": {
            "ytb_vos": {
                "root": "../../data/ytb_vos/crop511",
                "anno": "../../data/ytb_vos/train.json",
                "num_use": 200000,
                "frame_range": 20
            },
            "vid": {
                "root": "../../data/vid/crop511",
                "anno": "../../data/vid/train.json",
                "num_use": 200000,
                "frame_range": 100
            },
            "coco": {
                "root": "../../data/coco/crop511",
                "anno": "../../data/coco/train2017.json",
                "frame_range": 1
            },
            "det": {
                "root": "../../data/det/crop511",
                "anno": "../../data/det/train.json",
                "num_use": 100000,
                "frame_range": 1
            }
        },
        "template_size": 127,
        "search_size": 255,
        "base_size": 8,
        "size": 25,
        "num": 600000,
        "augmentation": {
            "template": {
                "shift": 4,
                "scale": 0.05
            },
            "search": {
                "shift": 64,
                "scale": 0.18,
                "blur": 0.18
            },
            "neg": 0.2,
            "gray": 0.25
        }
    },
    "val_datasets": {
        "datasets": {
            "vid": {
                "root": "../../data/vid/crop511",
                "anno": "../../data/vid/val.json",
                "num_use": 1000
            }
        },
        "template_size": 127,
        "search_size": 255,
        "size": 17,
        "num": 1000,
        "augmentation": {
            "template": {
                "shift": 0,
                "scale": 0.0
            },
            "search": {
                "shift": 12,
                "scale": 0.18
            },
            "neg": 0,
            "gray": 0
        }
    },
    "anchors": {
        "stride": 8,
        "ratios": [
            0.33,
            0.5,
            1,
            2,
            3
        ],
        "scales": [
            8
        ],
        "round_dight": 0
    },
    "clip": {
        "feature": 10.0,
        "rpn": 10.0,
        "split": false
    }
}
[2020-10-04 05:58:21,488-rk0-train_siammask.py# 78] build train dataset
[2020-10-04 05:58:21,488-rk0-siam_mask_dataset.py# 36] loading ../../data/ytb_vos/train.json
[2020-10-04 05:58:21,676-rk0-siam_mask_dataset.py# 74] ../../data/ytb_vos/train.json loaded.
[2020-10-04 05:58:21,764-rk0-siam_mask_dataset.py#134] SubDataSet ytb_vos start-index 0 select [200000/3000] path {}.{}.{}.jpg
[2020-10-04 05:58:21,764-rk0-siam_mask_dataset.py# 36] loading ../../data/vid/train.json
[2020-10-04 05:58:24,045-rk0-siam_mask_dataset.py# 74] ../../data/vid/train.json loaded.
[2020-10-04 05:58:24,132-rk0-siam_mask_dataset.py#134] SubDataSet vid start-index 3000 select [200000/3862] path {}.{}.{}.jpg
[2020-10-04 05:58:24,132-rk0-siam_mask_dataset.py# 36] loading ../../data/coco/train2017.json
[2020-10-04 05:58:26,252-rk0-siam_mask_dataset.py#118] Error, coco train2017/000000512390 12 [366.3, 120.6, 372.24, 120.6]
[2020-10-04 05:58:27,511-rk0-siam_mask_dataset.py# 74] ../../data/coco/train2017.json loaded.
[2020-10-04 05:58:27,571-rk0-siam_mask_dataset.py#134] SubDataSet coco start-index 6862 select [117266/117266] path {}.{}.{}.jpg
[2020-10-04 05:58:27,571-rk0-siam_mask_dataset.py# 36] loading ../../data/det/train.json
[2020-10-04 05:58:29,330-rk0-siam_mask_dataset.py#118] Error, det ILSVRC2014_train_0006/ILSVRC2014_train_00060036 01 [1, 498, 0, 498]
[2020-10-04 05:58:29,944-rk0-siam_mask_dataset.py# 74] ../../data/det/train.json loaded.
[2020-10-04 05:58:30,128-rk0-siam_mask_dataset.py#134] SubDataSet det start-index 124128 select [100000/333474] path {}.{}.{}.jpg
[2020-10-04 05:58:44,469-rk0-siam_mask_dataset.py#508] shuffle done!
[2020-10-04 05:58:44,469-rk0-siam_mask_dataset.py#509] dataset length 12000000
[2020-10-04 05:58:44,472-rk0-siam_mask_dataset.py#477] dataset informations: 
{
    "template": 127,
    "search": 255,
    "template_small": false,
    "gray": 0.25,
    "neg": 0.2,
    "inner_neg": 0,
    "crop_size": 0,
    "anchor_target": {
        "thr_high": 0.6,
        "thr_low": 0.3,
        "negative": 16,
        "rpn_batch": 64,
        "positive": 16
    },
    "num": 600000
}
[2020-10-04 05:58:59,017-rk0-siam_mask_dataset.py#508] shuffle done!
[2020-10-04 05:58:59,018-rk0-siam_mask_dataset.py#509] dataset length 12000000
[2020-10-04 05:58:59,021-rk0-train_siammask.py# 82] build val dataset
[2020-10-04 05:58:59,021-rk0-siam_mask_dataset.py# 36] loading ../../data/vid/val.json
[2020-10-04 05:58:59,695-rk0-siam_mask_dataset.py# 74] ../../data/vid/val.json loaded.
[2020-10-04 05:58:59,696-rk0-siam_mask_dataset.py#134] SubDataSet vid start-index 0 select [1000/555] path {}.{}.{}.jpg
[2020-10-04 05:58:59,697-rk0-siam_mask_dataset.py#508] shuffle done!
[2020-10-04 05:58:59,697-rk0-siam_mask_dataset.py#509] dataset length 1000
[2020-10-04 05:58:59,697-rk0-siam_mask_dataset.py#477] dataset informations: 
{
    "template": 127,
    "search": 255,
    "template_small": false,
    "gray": 0,
    "neg": 0,
    "inner_neg": 0,
    "crop_size": 0,
    "anchor_target": {
        "thr_high": 0.6,
        "thr_low": 0.3,
        "negative": 16,
        "rpn_batch": 64,
        "positive": 16
    },
    "num": 1000
}
[2020-10-04 05:58:59,698-rk0-siam_mask_dataset.py#508] shuffle done!
[2020-10-04 05:58:59,698-rk0-siam_mask_dataset.py#509] dataset length 1000
[2020-10-04 05:58:59,698-rk0-train_siammask.py# 93] build dataset done
[2020-10-04 05:58:59,901-rk0-load_helper.py# 31] load pretrained model from resnet.model
[2020-10-04 05:59:01,346-rk0-load_helper.py# 25] remove prefix 'module.'
[2020-10-04 05:59:01,347-rk0-load_helper.py# 13] [Warning] missing keys: {'layer3.4.bn2.num_batches_tracked', 'layer3.5.bn2.num_batches_tracked', 'layer3.4.bn1.num_batches_tracked', 'layer2.3.bn3.num_batches_tracked', 'layer2.0.bn3.num_batches_tracked', 'layer3.0.downsample.1.num_batches_tracked', 'layer1.2.bn2.num_batches_tracked', 'layer1.0.bn1.num_batches_tracked', 'layer3.1.bn2.num_batches_tracked', 'layer3.1.bn3.num_batches_tracked', 'layer3.1.bn1.num_batches_tracked', 'layer2.2.bn2.num_batches_tracked', 'layer2.2.bn3.num_batches_tracked', 'layer2.1.bn1.num_batches_tracked', 'layer2.0.downsample.1.num_batches_tracked', 'layer1.0.downsample.1.num_batches_tracked', 'layer2.1.bn2.num_batches_tracked', 'layer3.0.bn3.num_batches_tracked', 'layer3.0.bn1.num_batches_tracked', 'bn1.num_batches_tracked', 'layer1.2.bn3.num_batches_tracked', 'layer1.1.bn1.num_batches_tracked', 'layer3.3.bn2.num_batches_tracked', 'layer3.5.bn3.num_batches_tracked', 'layer1.0.bn2.num_batches_tracked', 'layer3.3.bn3.num_batches_tracked', 'layer3.2.bn1.num_batches_tracked', 'layer1.1.bn2.num_batches_tracked', 'layer2.3.bn1.num_batches_tracked', 'layer2.1.bn3.num_batches_tracked', 'layer2.2.bn1.num_batches_tracked', 'layer1.0.bn3.num_batches_tracked', 'layer3.3.bn1.num_batches_tracked', 'layer2.0.bn1.num_batches_tracked', 'layer3.2.bn2.num_batches_tracked', 'layer3.5.bn1.num_batches_tracked', 'layer1.1.bn3.num_batches_tracked', 'layer2.0.bn2.num_batches_tracked', 'layer1.2.bn1.num_batches_tracked', 'layer3.2.bn3.num_batches_tracked', 'layer3.4.bn3.num_batches_tracked', 'layer3.0.bn2.num_batches_tracked', 'layer2.3.bn2.num_batches_tracked'}
[2020-10-04 05:59:01,347-rk0-load_helper.py# 14] missing keys:43
[2020-10-04 05:59:01,347-rk0-load_helper.py# 16] [Warning] unused_pretrained_keys: {'layer4.0.bn2.weight', 'layer4.1.bn2.weight', 'layer4.1.bn1.weight', 'layer4.1.conv3.weight', 'layer4.1.conv1.weight', 'layer4.0.bn2.running_var', 'layer4.0.bn1.bias', 'layer4.0.bn2.bias', 'layer4.0.bn1.running_mean', 'layer4.1.bn2.running_var', 'layer4.1.bn1.bias', 'layer4.2.bn1.running_mean', 'layer4.0.bn3.running_mean', 'layer4.1.conv2.weight', 'layer4.2.bn3.weight', 'layer4.0.bn2.running_mean', 'layer4.0.bn3.weight', 'layer4.0.downsample.1.running_mean', 'layer4.2.conv3.weight', 'layer4.1.bn1.running_var', 'layer4.2.bn3.bias', 'layer4.2.bn3.running_mean', 'layer4.0.bn1.running_var', 'layer4.0.conv3.weight', 'layer4.2.bn2.weight', 'layer4.0.bn3.running_var', 'layer4.2.conv2.weight', 'layer4.2.bn2.running_var', 'layer4.0.downsample.0.weight', 'layer4.2.bn1.running_var', 'layer4.1.bn2.bias', 'layer4.0.downsample.1.bias', 'layer4.2.conv1.weight', 'layer4.2.bn1.weight', 'layer4.1.bn3.running_mean', 'layer4.2.bn3.running_var', 'layer4.0.downsample.1.weight', 'layer4.2.bn2.running_mean', 'layer4.0.conv1.weight', 'layer4.1.bn3.bias', 'layer4.1.bn3.weight', 'layer4.0.bn3.bias', 'layer4.1.bn3.running_var', 'layer4.2.bn2.bias', 'layer4.1.bn1.running_mean', 'layer4.2.bn1.bias', 'layer4.0.downsample.1.running_var', 'layer4.0.conv2.weight', 'layer4.0.bn1.weight', 'layer4.1.bn2.running_mean'}
[2020-10-04 05:59:01,347-rk0-load_helper.py# 17] unused checkpoint keys:50
[2020-10-04 05:59:01,347-rk0-load_helper.py# 18] used keys:215
[2020-10-04 05:59:01,358-rk0-features.py# 66] Current training 0 layers:	
[2020-10-04 05:59:01,359-rk0-features.py# 66] Current training 1 layers:	
[2020-10-04 05:59:01,384-rk0-train_siammask.py#146] Custom(
  (upSample): UpsamplingBilinear2d(size=[127, 127], mode=bilinear)
  (features): ResDown(
    (features): ResNet(
      (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace)
      (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
      (layer1): Sequential(
        (0): Bottleneck(
          (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace)
          (downsample): Sequential(
            (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
            (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (1): Bottleneck(
          (conv1): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace)
        )
        (2): Bottleneck(
          (conv1): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace)
        )
      )
      (layer2): Sequential(
        (0): Bottleneck(
          (conv1): Conv2d(256, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), bias=False)
          (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace)
          (downsample): Sequential(
            (0): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), bias=False)
            (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (1): Bottleneck(
          (conv1): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace)
        )
        (2): Bottleneck(
          (conv1): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace)
        )
        (3): Bottleneck(
          (conv1): Conv2d(512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace)
        )
      )
      (layer3): Sequential(
        (0): Bottleneck(
          (conv1): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
          (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace)
          (downsample): Sequential(
            (0): Conv2d(512, 1024, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
            (1): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (1): Bottleneck(
          (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(2, 2), dilation=(2, 2), bias=False)
          (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace)
        )
        (2): Bottleneck(
          (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(2, 2), dilation=(2, 2), bias=False)
          (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace)
        )
        (3): Bottleneck(
          (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(2, 2), dilation=(2, 2), bias=False)
          (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace)
        )
        (4): Bottleneck(
          (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(2, 2), dilation=(2, 2), bias=False)
          (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace)
        )
        (5): Bottleneck(
          (conv1): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(2, 2), dilation=(2, 2), bias=False)
          (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (conv3): Conv2d(256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False)
          (bn3): BatchNorm2d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          (relu): ReLU(inplace)
        )
      )
    )
    (downsample): ResDownS(
      (downsample): Sequential(
        (0): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
  )
  (rpn_model): UP(
    (cls): DepthCorr(
      (conv_kernel): Sequential(
        (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace)
      )
      (conv_search): Sequential(
        (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace)
      )
      (head): Sequential(
        (0): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace)
        (3): Conv2d(256, 10, kernel_size=(1, 1), stride=(1, 1))
      )
    )
    (loc): DepthCorr(
      (conv_kernel): Sequential(
        (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace)
      )
      (conv_search): Sequential(
        (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace)
      )
      (head): Sequential(
        (0): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace)
        (3): Conv2d(256, 20, kernel_size=(1, 1), stride=(1, 1))
      )
    )
  )
  (mask_model): MaskCorr(
    (mask): DepthCorr(
      (conv_kernel): Sequential(
        (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace)
      )
      (conv_search): Sequential(
        (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace)
      )
      (head): Sequential(
        (0): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU(inplace)
        (3): Conv2d(256, 3969, kernel_size=(1, 1), stride=(1, 1))
      )
    )
  )
)
[2020-10-04 05:59:01,406-rk0-train_siammask.py#164] (WarmUPScheduler) lr spaces: 
[0.001      0.00137973 0.00190365 0.00262653 0.0036239  0.005
 0.00475848 0.00452862 0.00430986 0.00410168 0.00390355 0.00371499
 0.00353553 0.00336475 0.00320222 0.00304753 0.00290032 0.00276022
 0.00262689 0.0025    ]
[2020-10-04 05:59:01,406-rk0-train_siammask.py#166] model prepare done
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
Traceback (most recent call last):
  File "/home/honda/SiamMask/tools/train_siammask.py", line 292, in <module>
    main()
  File "/home/honda/SiamMask/tools/train_siammask.py", line 168, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, args.start_epoch, cfg)
  File "/home/honda/SiamMask/tools/train_siammask.py", line 236, in train
    outputs = model(x)
  File "/home/honda/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/honda/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 121, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/honda/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/honda/SiamMask/models/siammask.py", line 96, in forward
    self.run(template, search, softmax=self.training)
  File "/home/honda/SiamMask/models/siammask.py", line 61, in run
    template_feature = self.feature_extractor(template)
  File "/home/honda/SiamMask/models/siammask.py", line 37, in feature_extractor
    return self.features(x)
  File "/home/honda/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/honda/SiamMask/experiments/siammask_base/custom.py", line 58, in forward
    output = self.features(x)
  File "/home/honda/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/honda/SiamMask/experiments/siammask_base/resnet.py", line 219, in forward
    x = self.conv1(x)
  File "/home/honda/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/honda/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THC/THCGeneral.cpp:663

Please, some advice

**Comment by makifozkanoglu** [comment]
you may solve by changing your torch version, I remember this approach was a solution for me. otherwise it is resulted from mismatch version of cuda etc

**Comment by honda12345** [comment]
tahanks! it's solved.

**Comment by honda12345** [comment]
thanks! it's solved

**Comment by AlexanderMath** [comment]
Which version did you have to update too? I have had the issue with torch 0.4.1, 1.3.1, 1.1.0 and 1.8.0

**Comment by danho47** [comment]
it worked fine with the latest version of PyTorch in Oct 2020. Probably 1.6.0 or 1.7.0
