### ISSUE TITLE
When I used the Window system to train the code, the code reported an error：'>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by White-Jiang-x** [foolwood/SiamMask#183]
Traceback (most recent call last):
  File "D:/SiamMask/tools/train_siammask.py", line 296, in <module>
    main()
  File "D:/SiamMask/tools/train_siammask.py", line 170, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, args.start_epoch, cfg)
  File "D:/SiamMask/tools/train_siammask.py", line 188, in train
    for iter, input in enumerate(train_loader):
  File "D:\Anaconda\envs\mask\lib\site-packages\torch\utils\data\dataloader.py", line 314, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "D:\Anaconda\envs\mask\lib\site-packages\torch\utils\data\dataloader.py", line 314, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "D:\SiamMask\datasets\siam_mask_dataset.py", line 551, in __getitem__
    search_mask = (cv2.imread(search[2], 0) > 0).astype(np.float32)
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by shupingbaba** [comment]
I have the same problem. Have you solved it?

**Comment by White-Jiang-x** [comment]
> I have the same problem. Have you solved it?

I did not have this error when I run it on the linxu system, maybe you should use the linxu system to run it

**Comment by shupingbaba** [comment]
Thanks you for answer,but i am using Ubuntu and this problem still occurs.

**Comment by ahmedosamaz** [comment]
i have the same problem
have any found a solve ??

search_mask = (cv2.imread(search[2], 0) > 0).astype(np.float32)
TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by tm9161** [comment]
I have the same problem

TypeError: '>' not supported between instances of 'NoneType' and 'int'

**Comment by ping-shu** [comment]
> I have the same problem
> 
> TypeError: '>' not supported between instances of 'NoneType' and 'int'

It should be a data set problem, and it should be reprocessed according to the data set processing method in SiamMask

**Comment by tm9161** [comment]
> > I have the same problem
> > TypeError: '>' not supported between instances of 'NoneType' and 'int'
> 
> It should be a data set problem, and it should be reprocessed according to the data set processing method in SiamMask

Thanks ,I crop the data set again and this problem disappeared .

**Comment by ulyana2002** [comment]
Подскажите, пожалуйста как именно вы обрезали набор данных ?

**Comment by sangeun-jo** [comment]
I had same error. I printed search[2], that image file wasn't exist. I removed that file and then error was gone. 
If you have too many missing files consider redo crop process.
