### ISSUE TITLE
The proble in running test

### ISSUE THREAD

**Issue by shupingbaba** [foolwood/SiamMask#187]
python ../../tools/eval.py --dataset VOT2018 --tracker_prefix C --result_dir ./test/VOT2018
loading VOT2018:   0%|                                                       | 0loading VOT2018:   0%|                                                | 0/60 [00:00<?, ?it/s, ants1]Traceback (most recent call last):
  File "../../tools/eval.py", line 36, in <module>
    dataset = VOTDataset(args.dataset, root)
  File "/home/shuping/daima/SiamMask-master/utils/pysot/datasets/vot.py", line 124, in __init__
    meta_data[video]['width'],
KeyError: 'width

**Comment by shupingbaba** [comment]
Solved, json file problem, download the official file
