### ISSUE TITLE
 eval: max() arg is an empty sequence

### ISSUE THREAD

**Issue by BaBaWen** [foolwood/SiamMask#189]
请问，我在对SiamMask_VOT 进行评估的时候，在EAO 时候提示如标题所示，错误如下：
loading VOT2019: 100%|████████████████████████████████| 60/60 [00:00<00:00, 1002.65it/s, zebrafish1]
eval ar: 100%|████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.65it/s]
eval eao:   0%|                                                               | 0/1 [00:00<?, ?it/s]
multiprocessing.pool.RemoteTraceback: 
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\py37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Administrator\Desktop\python\SiamMask\utils\pysot\evaluation\eao_benchmark.py", line 52, in eval
    eao = self._calculate_eao(tracker_name, self.tags)
  File "C:\Users\Administrator\Desktop\python\SiamMask\utils\pysot\evaluation\eao_benchmark.py", line 111, in _calculate_eao
    max_len = max([len(x) for x in all_overlaps])
ValueError: max() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/python/SiamMask/tools/eval.py", line 55, in <module>
    trackers), desc='eval eao', total=len(trackers), ncols=100):
  File "C:\Users\Administrator\anaconda3\envs\py37\lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\Administrator\anaconda3\envs\py37\lib\multiprocessing\pool.py", line 748, in next
    raise value
ValueError: max() arg is an empty sequence

我尝试过用单独的pysot -toolkit进行测试，但是仍然是这样，我怀疑是test结果格式错误，不知道你们有没有遇到这个问题

**Comment by estrelasy** [comment]
您好，我也有同样的问题，请问解决了吗，可不可以分享一下怎么解决呢

**Comment by aalessi3** [comment]
Has anyone made progress on this issue?
