### ISSUE TITLE
the problem in trainning  

### ISSUE THREAD

**Issue by FUTUREEEEE** [foolwood/SiamMask#191]
Traceback (most recent call last):
  File "/home/chen/anaconda3/envs/siammask/lib/python3.6/multiprocessing/resource_sharer.py", line 142, in _serve
    with self._listener.accept() as conn:
  File "/home/chen/anaconda3/envs/siammask/lib/python3.6/multiprocessing/connection.py", line 455, in accept
    deliver_challenge(c, self._authkey)
  File "/home/chen/anaconda3/envs/siammask/lib/python3.6/multiprocessing/connection.py", line 722, in deliver_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/home/chen/anaconda3/envs/siammask/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/chen/anaconda3/envs/siammask/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/chen/anaconda3/envs/siammask/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError

**Comment by FUTUREEEEE** [comment]
This problem appeared after 1% training
