### ISSUE TITLE
cv2.error resize

### ISSUE THREAD

**Issue by CielYue** [foolwood/SiamMask#20]
Traceback (most recent call last):
  File "../../tools/demo.py", line 52, in <module>
    state = siamese_init(im, target_pos, target_sz, siammask, cfg['hp'])  # init tracker
  File "/home/lut/SiamMask/tools/test.py", line 157, in siamese_init
    z_crop = get_subwindow_tracking(im, target_pos, p.exemplar_size, s_z, avg_chans)
  File "/home/lut/SiamMask/tools/test.py", line 109, in get_subwindow_tracking
    im_patch = cv2.resize(im_patch_original, (model_sz, model_sz))
cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

**Comment by outfielder** [comment]
Did you/anyone find a solutoin to this?
