### ISSUE TITLE
  File "../../tools/demo.py", line 7, in <module>     from tools.test import * ModuleNotFoundError: No module named 'tools'

### ISSUE THREAD

**Issue by ssshcj** [foolwood/SiamMask#35]
run python ../../tools/demo.py --resume SiamMask_DAVIS.pth --config config_davis.json and get a error:
Traceback (most recent call last):
  File "../tools/demo.py", line 7, in <module>
    from tools.test import *
ModuleNotFoundError: No module named 'tools'
Can someone help me solve this problem? Thank you.

**Comment by lzdibng** [comment]
I meet the same question.Have you solve it?

**Comment by foolwood** [comment]
```
ROOT=`git rev-parse --show-toplevel`
export PYTHONPATH=$ROOT:$PYTHONPATH
export PYTHONPATH=$PWD:$PYTHONPATH
```

You should add SiamMask Root to `PYTHONPATH`.
Thanks.

**Comment by lzdibng** [comment]
Thank you for your quick reply.

I changed the siamMask file names,but I forgot changed the PYTHONPATH. 

But now I have a new problem :No module named custom.Can you help me?

Thanks so much!





------------------ 原始邮件 ------------------
发件人: "Qiang Wang"<notifications@github.com>;
发送时间: 2019年5月6日(星期一) 下午4:25
收件人: "foolwood/SiamMask"<SiamMask@noreply.github.com>;
抄送: "冷暖自知。"<609921748@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [foolwood/SiamMask]   File "../../tools/demo.py", line 7, in<module>     from tools.test import * ModuleNotFoundError: No module named'tools' (#35)



ROOT=`git rev-parse --show-toplevel` export PYTHONPATH=$ROOT:$PYTHONPATH export PYTHONPATH=$PWD:$PYTHONPATH  
You should add SiamMask Root to PYTHONPATH.
 Thanks.

**Comment by foolwood** [comment]
@lzdibng 
You should also add `SiamMask/experiments/siammask_sharp` to `PYTHONPATH`.
```
cd $SiamMask/experiments/siammask_sharp 
export PYTHONPATH=$PWD:$PYTHONPATH
```

**Comment by ssshcj** [comment]
Thanks，I will try.

**Comment by lzdibng** [comment]
I am sorry that I did not reply to you in time.
I have test it successfully!
It is really a great project！
Can you open up its training code and training details, I want to know more about it, it is very helpful to me.
Thanks so much.
Best regards！



------------------ 原始邮件 ------------------
发件人: "Qiang Wang"<notifications@github.com>;
发送时间: 2019年5月6日(星期一) 下午4:47
收件人: "foolwood/SiamMask"<SiamMask@noreply.github.com>;
抄送: "冷暖自知。"<609921748@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [foolwood/SiamMask]   File "../../tools/demo.py", line 7, in<module>     from tools.test import * ModuleNotFoundError: No module named'tools' (#35)




@lzdibng
 You should also add SiamMask/experiments/siammask_sharp to PYTHONPATH.
 cd $SiamMask/experiments/siammask_sharp  export PYTHONPATH=$PWD:$PYTHONPATH

**Comment by pranavshukla1011** [comment]
![image](https://user-images.githubusercontent.com/55877875/103506774-8bea4300-4e83-11eb-8d92-b952b30ddf57.png)

I have added my siammask root folder as well as SiamMask/experiments/siammask_sharp to PYTHONPATH.

I'm still getting the same error.

Traceback (most recent call last):
  File "C:\Users\hp\SiamMask\tools\demo.py", line 7, in <module>
    from tools.test import *
ModuleNotFoundError: No module named 'tools'

could someone help me out?
