### ISSUE TITLE
run demo.py error

### ISSUE THREAD

**Issue by ZhaoMonica** [foolwood/SiamMask#41]
python3 ../../tools/demo.py --resume SiamMask_DAVIS.pth --config config_davis.json
[2019-05-14 16:31:21,238-rk0-load_helper.py# 31] load pretrained model from SiamMask_DAVIS.pth
[2019-05-14 16:31:23,679-rk0-load_helper.py# 25] remove prefix 'module.'
[2019-05-14 16:31:23,680-rk0-load_helper.py# 18] used keys:356
Xlib:  extension "RANDR" missing on display ":0".
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!
/home/sdu/.local/lib/python3.5/site-packages/torch/nn/functional.py:1890: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
Traceback (most recent call last):
  File "../../tools/demo.py", line 54, in <module>
    state = siamese_track(state, im, mask_enable=True, refine_enable=True)  # track
  File "/home/sdu/SiamMask/tools/test.py", line 285, in siamese_track
    _, contours, _ = cv2.findContours(target_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
ValueError: not enough values to unpack (expected 3, got 2)

I haven't corrected the code in it, but after drawing the area and entering the "Enter" key, the above error occurred. Do you have a solution? Thank you very much.

**Comment by Bayrambai** [comment]
It is the issue of opencv. I hope following line of code will help:
`if cv2.__version__.split('.')[0] == 3:
_, contours, _ = cv2.findContours()
else:
contours, _ = cv2.findContours()`

**Comment by zhb96** [comment]
python ../../tools/demo.py --resume SiamMask_DAVIS.pth --config config_davis.json
Traceback (most recent call last):
  File "../../tools/demo.py", line 20, in <module>
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
AttributeError: 'module' object has no attribute 'device'

when I run the demo.py, ERROR occurred as above. How can I solve the problem?
