### ISSUE TITLE
Cython.Compiler.Errors.CompileError: region.pyx

### ISSUE THREAD

**Issue by EternityZY** [foolwood/SiamMask#60]
when I run the bash make.sh, I will get this problem

python setup.py build_ext --inplace
Compiling region.pyx because it changed.
Cythonizing region.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdio cimport sprintf
from libc.string cimport strlen

cimport c_region

cpdef enum RegionType:
     ^
------------------------------------------------------------

region.pyx:10:6: C struct/union/enum cannot be declared cpdef

Error compiling Cython file:
------------------------------------------------------------
...
    return overlaps

def vot_float2str(template, float value):
    cdef bytes ptemplate = template.encode()   
    cdef const char* ctemplate = ptemplate
                  ^
------------------------------------------------------------

region.pyx:233:19: Syntax error in C variable declaration
Traceback (most recent call last):
  File "setup.py", line 14, in <module>
    ext_modules = cythonize([Extension("region", ["region.pyx"])])
  File "python_package/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 667, in cythonize
    cythonize_one(*args[1:])
  File "python_package/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 731, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: region.pyx

How to solve it?

**Comment by petrick23** [comment]
i also get this. setup.py cant compile the region.pyx, so the tools.test cant import region

**Comment by MIXALER** [comment]
the same issue!

**Comment by heathentw** [comment]
Any solution yet @@?

**Comment by molefeskymleya** [comment]
hi guys... you can manually 
`cd pathto/SiamMask/utils/pysot/utils/` then open region.c

after that open [https://github.com/foolwood/SiamMask/blob/master`/utils/pysot/utils/region.c`](url) and copy the content in that file to `../utils/pysot/utils/region.c` on your computer.

do the same for [https://github.com/foolwood/SiamMask/blob/master/utils/pyvotkit/region.c](url) and copy that to your computer.

after that, you won't have this problem with  running `bash make.sh`

**Comment by MuskAI** [comment]
I solve it successfully by pip install Cython==0.29.24 can solve it.
