### ISSUE TITLE
where can i get /snapshot/checkpoint_e9.pth?

### ISSUE THREAD

**Issue by gyftsy** [foolwood/SiamMask#76]
[2019-07-24 10:17:53,928-rk0-load_helper.py# 58] restore from snapshot/checkpoint_e9.pth
Traceback (most recent call last):
  File "/home/ai/PycharmProjects/SiamMask/experiments/siammask_base/tools/train_siammask.py", line 292, in <module>
    main()
  File "/home/ai/PycharmProjects/SiamMask/experiments/siammask_base/tools/train_siammask.py", line 161, in main
    model, optimizer, args.start_epoch, best_acc, arch = restore_from(model, optimizer, args.resume)
  File "/home/ai/PycharmProjects/SiamMask/experiments/siammask_base/utils/load_helper.py", line 60, in restore_from
    ckpt = torch.load(ckpt_path, map_location=lambda storage, loc: storage.cuda(device))
  File "/home/ai/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/ai/anaconda3/envs/siammask/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
EOFError: Ran out of input

hi! when I wanna run the run.sh(in cd $SiamMask/experiments/siammask_base/). I met an error.The program said that it need restore /snapshot/checkpoint_e9.pth.But there have no this document.I just thought it should be to build up in this program(weight). and i can get this document from your project.could u help me?thank u very much!

**Comment by gyftsy** [comment]
Traceback (most recent call last):
  File "/home/ai/PycharmProjects/SiamMask/experiments/siammask_base/tools/train_siammask.py", line 292, in <module>
    main()
  File "/home/ai/PycharmProjects/SiamMask/experiments/siammask_base/tools/train_siammask.py", line 160, in main
    assert os.path.isfile(args.resume), '{} is not a valid file'.format(args.resume)
AssertionError: snapshot/checkpoint_e9.pth is not a valid file

**Comment by fyaft2012** [comment]
Did you solve this problem? I met same error with you.

Traceback (most recent call last):
  File "/home/aiserver/fangyang/SiamMask/SiamMask-master/tools/train_siammask.py", line 292, in <module>
    main()
  File "/home/aiserver/fangyang/SiamMask/SiamMask-master/tools/train_siammask.py", line 160, in main
    assert os.path.isfile(args.resume), '{} is not a valid file'.format(args.resume)
AssertionError: snapshot/checkpoint_e9.pth is not a valid file
test snapshot 1 /root 20 on dataset VOT2016 with 4 gpus.

**Comment by gyftsy** [comment]
这实际上是一个端点训练 如果你从一开始训练的话就把这句话去掉 如果你训练了一半 那就换成你训练的权值


发自我的iPhone

------------------ Original ------------------

**Comment by fyaft2012** [comment]
你好，gyftsy ：
 可否再具体指导一下， 具体是在那个文件里的代码呢？

**Comment by gyftsy** [comment]
就是run.sh文件的代码 去掉报错的那句话




发自我的iPhone

------------------ Original ------------------

**Comment by fyaft2012** [comment]
好的， 目前没有显示这个错误了，非常感谢！

**Comment by fyaft2012** [comment]
你好 gyftsy，可以再请教你个问题吗？ 现在又出现了新的问题：

File "/home/aiserver/fangyang/SiamMask/SiamMask-master/experiments/siammask_sharp/custom.py", line 150, in forward
    out = self.post0(F.upsample(self.h2(out) + self.v2(p2), size=(31, 31)))
**RuntimeError: The size of tensor a (5000) must match the size of tensor b (2312) at non-singleton dimension 0**
test snapshot 1 /root 20 on dataset VOT2016 with 4 gpus.
[2019-07-29 18:13:21,286-rk0-test.py#555] Namespace(arch='Custom', config='config.json', cpu=False, dataset='VOT2016', debug=False, gt=False, log='log_test.txt', mask=True, refine=False, resume='snapshot/checkpoint_e2.pth', save_mask=False, video='', visualization=False)
[2019-07-29 18:13:21,344-rk0-test.py#555] Namespace(arch='Custom', config='config.json', cpu=False, dataset='VOT2016', debug=False, gt=False, log='log_test.txt', mask=True, refine=False, resume='snapshot/checkpoint_e19.pth', save_mask=False, ........

请问你在训练过程中遇到过这个问题吗？谢谢~

**Comment by liudaizong** [comment]
> 你好 gyftsy，可以再请教你个问题吗？ 现在又出现了新的问题：
> 
> File "/home/aiserver/fangyang/SiamMask/SiamMask-master/experiments/siammask_sharp/custom.py", line 150, in forward
> out = self.post0(F.upsample(self.h2(out) + self.v2(p2), size=(31, 31)))
> **RuntimeError: The size of tensor a (5000) must match the size of tensor b (2312) at non-singleton dimension 0**
> test snapshot 1 /root 20 on dataset VOT2016 with 4 gpus.
> [2019-07-29 18:13:21,286-rk0-test.py#555] Namespace(arch='Custom', config='config.json', cpu=False, dataset='VOT2016', debug=False, gt=False, log='log_test.txt', mask=True, refine=False, resume='snapshot/checkpoint_e2.pth', save_mask=False, video='', visualization=False)
> [2019-07-29 18:13:21,344-rk0-test.py#555] Namespace(arch='Custom', config='config.json', cpu=False, dataset='VOT2016', debug=False, gt=False, log='log_test.txt', mask=True, refine=False, resume='snapshot/checkpoint_e19.pth', save_mask=False, ........
> 
> 请问你在训练过程中遇到过这个问题吗？谢谢~

你是怎么解决的？

**Comment by hzy5660251** [comment]
@fyaft2012 老哥，The size of tensor a (5000) must match the size of tensor b (2312) at non-singleton dimension 0这个错误你最后怎么解决的呀

**Comment by zzzmm1** [comment]
@fyaft2012 @hzy5660251 @liudaizong 上述错误有人最后解决了吗？我也困在这里了。

**Comment by yjkupup** [comment]
@gyftsy 
您好，请问这个resume代表的是断点续训的意思吗？如果利用resnet.model从头开始训练就在run.sh里面把--resume这句话去掉，假设训练到第5个epoch停了，就在resume后面加上checkpoint_e4.pth,从第五个epoch开始训练。是这个意思吗？

**Comment by yjkupup** [comment]
@zzzmm1 您好，请问您训练siammask达到作者的效果了吗？
