### ISSUE TITLE
no such file or directory:

### ISSUE THREAD

**Issue by liuzhongshen** [foolwood/SiamMask#79]
Traceback (most recent call last):
  File "/home/lw/SiamMask/tools/train_siammask.py", line 292, in <module>
    main()
  File "/home/lw/SiamMask/tools/train_siammask.py", line 139, in main
    train_loader, val_loader = build_data_loader(cfg)
  File "/home/lw/SiamMask/tools/train_siammask.py", line 79, in build_data_loader
    train_set = DataSets(cfg['train_datasets'], cfg['anchors'], args.epochs)
  File "/home/lw/SiamMask/datasets/siam_mask_dataset.py", line 445, in __init__
    dataset = SubDataSet(dataset)
  File "/home/lw/SiamMask/datasets/siam_mask_dataset.py", line 35, in __init__
    with open(cfg['anno']) as fin:
FileNotFoundError: [Errno 2] No such file or directory: '../../data/ytb_vos/train.json'
test_all.sh: line 12: activate: No such file or directory

**Comment by liuzhongshen** [comment]
problem:datasets are not configed

**Comment by asuleyman** [comment]
How did you solve this error ?
