### ISSUE TITLE
bash run.sh gives RuntimeError: The size of tensor a (5000) must match the size of tensor b (2312) at non-singleton dimension 0

### ISSUE THREAD

**Issue by fyaft2012** [foolwood/SiamMask#82]
Hi @foolwood, thank you very much for your great work, I can successfully run demo and VOT test, however when I run training script of base siammask model with commend "**bash run.sh**",  it gave the error message:
[2019-07-29 21:26:06,194-rk0-train_siammask.py#166] model prepare done
Traceback (most recent call last):
  File "/home/aiserver/fangyang/SiamMask/SiamMask-master/tools/train_siammask.py", line 292, in <module>
    main()
  File "/home/aiserver/fangyang/SiamMask/SiamMask-master/tools/train_siammask.py", line 168, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, args.start_epoch, cfg)
  File "/home/aiserver/fangyang/SiamMask/SiamMask-master/tools/train_siammask.py", line 236, in train
    outputs = model(x)
  File "/home/aiserver/fangyang/anaconda3/envs/siammask-tracker/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aiserver/fangyang/anaconda3/envs/siammask-tracker/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 124, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/aiserver/fangyang/anaconda3/envs/siammask-tracker/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 134, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/aiserver/fangyang/anaconda3/envs/siammask-tracker/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 77, in parallel_apply
    raise output
  File "/home/aiserver/fangyang/anaconda3/envs/siammask-tracker/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 53, in _worker
    output = module(*input, **kwargs)
  File "/home/aiserver/fangyang/anaconda3/envs/siammask-tracker/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aiserver/fangyang/SiamMask/SiamMask-master/models/siammask_sharp.py", line 97, in forward
    self.run(template, search, softmax=self.training)
  File "/home/aiserver/fangyang/SiamMask/SiamMask-master/models/siammask_sharp.py", line 65, in run
    rpn_pred_mask = self.refine_model(feature, corr_feature)
  File "/home/aiserver/fangyang/anaconda3/envs/siammask-tracker/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/aiserver/fangyang/SiamMask/SiamMask-master/experiments/siammask_sharp/custom.py", line 150, in forward
    **out = self.post0(F.upsample(self.h2(out) + self.v2(p2), size=(31, 31)))
RuntimeError: The size of tensor a (5000) must match the size of tensor b (2312) at non-singleton dimension 0**
test snapshot 1 /root 20 on dataset VOT2016 with 2 gpus.
[2019-07-29 21:26:48,783-rk0-test.py#555] Namespace(arch='Custom', config='config.json', cpu=False, dataset='VOT2016', debug=False, gt=False, log='log_test.txt', mask=True, refine=False, resume='snapshot/checkpoint_e13.pth', save_mask=False, video='', visualization=False).......

Could you give me a help? Looking for your reply, thanks!

**Comment by fyaft2012** [comment]
By the way, since there is CUDA error: out-of-memory, I changed batch size from 64 to 16. The above problem occurred.

**Comment by IrectionD** [comment]
I got the same problem where I changed batch size from 64 to 8. How can I solve this?

**Comment by Bradyeyi** [comment]
I think that the refine model has a problem. the result of 'p0 = F.unfold(f[0], (61, 61), padding=0, stride=4).permute(0, 2, 1).contiguous().view(-1, 64, 61, 61)' should be  b * c * 17 * 17.But the corr_feature  is b * c  * 25 * 25, the size can't match. Because in the adjustlayer model, the code is 
                 if  x.size(3) < 20:
                       l = 4
                       r = l+ 7
                       x = x[:, :,  l:r, l:r]
                return x
         so the template output feature size is  b * c  * 7 * 7. when you delete this part , you can practice the result of paper, the row is 17*17*256.I have done it ,but the result is bad. because Row become smaller.At the same time, when you test the trained model, if you face this state----- in the select_ROI the object occupy in the center of box, but object has lower rate than background in the box. The model only learn more background feature , it cause that the tracker is failure. 
         Therefore, I don't advise you delete this part code, you can modify the padding (0-16，0-8， 0-4）.Just like in the test state, the refine model does a padding. I am trying it , but the batch size is a problem. I set batch size 2, it still appears ' CUDA out of memory' . when I set batch size 1, the mask_loss is 0. Train it , are you kidding  me?My computer performance is too poor.Why do I choose CV? Autism!

**Comment by LANMNG** [comment]
@fyaft2012  I meet the same question, and i solved it in a funny way, if you use multi-GPU, such as four GPU, you must keep the first GPU empty without any use, i failed because root`s 55M used in my first GPU, you may reboot your server and then try it again.

**Comment by Damon2019** [comment]
Excuse me，have you successfully changed the data set and trained?
If you succeed, can you tell me how to do that?thanks!

**Comment by hzy5660251** [comment]
@fyaft2012 Hi, How did you solve this problem at last? Is it in connection with multi-GPU?

**Comment by hzy5660251** [comment]
@Bradyeyi I tried your second solution and changed padding, but also get the bad results(bathchsize=2)

**Comment by Bradyeyi** [comment]
@hzy5660251  if you read the paper of siamMask, you should use first solution to generate corr_feature (b * c * 17 * 17)。
![image](https://user-images.githubusercontent.com/39555917/70764135-9118b380-1d91-11ea-9fe8-a27c5cc39a51.png)

**Comment by hzy5660251** [comment]
@Bradyeyi I'll try!thx!

**Comment by hzy5660251** [comment]
@fyaft2012 Hi！How did u solve this problem at last? thx!

**Comment by zzzmm1** [comment]
I met the same problem. Whats the final solution?
