### ISSUE TITLE
run demo.py

### ISSUE THREAD

**Issue by 1wanttoknow** [foolwood/SiamMask#83]
(siammask) user@..:/media/user/hard/li/SiamMask/experiments/siammask_sharp$ python ../../tools/demo.py --resume SiamMask_DAVIS.pth --config config_davis.json
[2019-08-06 11:00:43,613-rk0-features.py# 66] Current training 0 layers:

[2019-08-06 11:00:43,614-rk0-features.py# 66] Current training 1 layers:

[2019-08-06 11:00:43,714-rk0-load_helper.py# 31] load pretrained model from SiamMask_DAVIS.pth
Traceback (most recent call last):
  File "../../tools/demo.py", line 30, in <module>
    siammask = load_pretrain(siammask, args.resume)
  File "/media/user/hard/li/SiamMask/utils/load_helper.py", line 36, in load_pretrain
    pretrained_dict = torch.load(pretrained_path, map_location=lambda storage, loc: storage.cuda(device))
  File "/home/user/miniconda3/envs/siammask/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/user/miniconda3/envs/siammask/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '<'.
what should i do?

**Comment by 1wanttoknow** [comment]
Network problems, things that need to be downloaded, do not need "wget, git", download them separately and put them in the right place.
