### ISSUE TITLE
"bash test_mask_refine.sh config_davis.json" output size question

### ISSUE THREAD

**Issue by Hahaemmm** [foolwood/SiamMask#86]
when i try to run :
bash test_mask_refine.sh config_davis.json SiamMask_DAVIS.pth DAVIS2017 0
[2019-08-06 22:51:57,339-rk0-test.py#555] Namespace(arch=u'Custom', config='config_davis.json', cpu=False, dataset='DAVIS2017', debug=False, gt=False, log='log_test.txt', mask=True, refine=True, resume='SiamMask_DAVIS.pth', save_mask=False, video='', visualization=False)
[2019-08-06 22:51:57,804-rk0-features.py# 66] Current training 0 layers:

[2019-08-06 22:51:57,806-rk0-features.py# 66] Current training 1 layers:

[2019-08-06 22:51:57,905-rk0-load_helper.py# 31] load pretrained model from SiamMask_DAVIS.pth
[2019-08-06 22:52:03,409-rk0-load_helper.py# 25] remove prefix 'module.'
[2019-08-06 22:52:03,414-rk0-load_helper.py# 16] [Warning] unused_pretrained_keys: set([u'features.features.layer2.2.bn1.num_batches_tracked', u'features.features.layer2.1.bn2.num_batches_tracked', u'rpn_model.loc.conv_kernel.1.num_batches_tracked', u'features.features.layer3.2.bn1.num_batches_tracked', u'rpn_model.cls.conv_search.1.num_batches_tracked', u'features.features.layer3.2.bn3.num_batches_tracked', u'features.features.layer3.1.bn2.num_batches_tracked', u'features.features.layer2.0.bn2.num_batches_tracked', u'features.features.layer2.3.bn2.num_batches_tracked', u'features.features.layer3.1.bn3.num_batches_tracked', u'rpn_model.loc.conv_search.1.num_batches_tracked', u'features.downsample.downsample.1.num_batches_tracked', u'features.features.layer1.2.bn1.num_batches_tracked', u'features.features.layer3.0.bn3.num_batches_tracked', u'features.features.layer1.1.bn3.num_batches_tracked', u'features.features.layer3.3.bn1.num_batches_tracked', u'features.features.layer1.2.bn2.num_batches_tracked', u'features.features.layer3.0.bn1.num_batches_tracked', u'mask_model.mask.conv_kernel.1.num_batches_tracked', u'features.features.layer2.3.bn3.num_batches_tracked', u'features.features.layer1.0.bn1.num_batches_tracked', u'features.features.layer3.1.bn1.num_batches_tracked', u'features.features.layer3.4.bn2.num_batches_tracked', u'features.features.layer2.3.bn1.num_batches_tracked', u'features.features.layer2.2.bn3.num_batches_tracked', u'features.features.layer1.1.bn2.num_batches_tracked', u'features.features.layer2.0.bn3.num_batches_tracked', u'features.features.layer3.4.bn1.num_batches_tracked', u'features.features.layer3.3.bn3.num_batches_tracked', u'features.features.layer1.1.bn1.num_batches_tracked', u'rpn_model.cls.conv_kernel.1.num_batches_tracked', u'features.features.layer3.3.bn2.num_batches_tracked', u'features.features.layer3.4.bn3.num_batches_tracked', u'features.features.layer2.2.bn2.num_batches_tracked', u'features.features.layer1.2.bn3.num_batches_tracked', u'rpn_model.loc.head.1.num_batches_tracked', u'features.features.layer3.5.bn3.num_batches_tracked', u'features.features.layer2.1.bn3.num_batches_tracked', u'features.features.layer1.0.downsample.1.num_batches_tracked', u'rpn_model.cls.head.1.num_batches_tracked', u'features.features.layer2.0.downsample.1.num_batches_tracked', u'features.features.layer3.0.downsample.1.num_batches_tracked', u'features.features.layer1.0.bn2.num_batches_tracked', u'features.features.bn1.num_batches_tracked', u'features.features.layer3.5.bn2.num_batches_tracked', u'features.features.layer3.5.bn1.num_batches_tracked', u'features.features.layer2.1.bn1.num_batches_tracked', u'mask_model.mask.conv_search.1.num_batches_tracked', u'features.features.layer3.2.bn2.num_batches_tracked', u'features.features.layer2.0.bn1.num_batches_tracked', u'features.features.layer3.0.bn2.num_batches_tracked', u'mask_model.mask.head.1.num_batches_tracked', u'features.features.layer1.0.bn3.num_batches_tracked'])
[2019-08-06 22:52:03,415-rk0-load_helper.py# 17] unused checkpoint keys:53
[2019-08-06 22:52:03,415-rk0-load_helper.py# 18] used keys:303
Traceback (most recent call last):
  File "/home/caixianchen/SiamMask/tools/test.py", line 608, in <module>
    main()
  File "/home/caixianchen/SiamMask/tools/test.py", line 589, in main
    args.mask, args.refine, args.dataset in ['DAVIS2017', 'ytb_vos'], device=device)
  File "/home/caixianchen/SiamMask/tools/test.py", line 500, in track_vos
    state = siamese_track(state, im, mask_enable, refine_enable, device=device)  # track
  File "/home/caixianchen/SiamMask/tools/test.py", line 257, in siamese_track
    mask = net.track_refine((delta_y, delta_x)).to(device).sigmoid().squeeze().view(
  File "/home/caixianchen/SiamMask/experiments/siammask_sharp/custom.py", line 189, in track_refine
    pred_mask = self.refine_model(self.feature, self.corr_feature, pos=pos, test=True)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/caixianchen/SiamMask/experiments/siammask_sharp/custom.py", line 150, in forward
    out = self.post0(F.upsample(self.h2(out) + self.v2(p2), size=(31, 31)))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 1755, in upsample
    return torch._C._nn.upsample_nearest2d(input, _scale_factor(2))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/functional.py", line 1727, in _scale_factor
    'x'.join(map(str, input.size()))))
RuntimeError: output size specified in UpsamplingNearest (31x31) has to be divisible by the input size, but got: 1x32x15x15

**Comment by eathongdoubin** [comment]
I have encountered the same problem with you. Have you solved it?

**Comment by Hahaemmm** [comment]
> I have encountered the same problem with you. Have you solved it?

I solved this problem after I reinstalled the environment.

**Comment by eathongdoubin** [comment]
不好意思啊 我是一个新手 请问具体是什么环境呢😭

**Comment by Hahaemmm** [comment]
> 不好意思啊 我是一个新手 请问具体是什么环境呢😭

说出来你可能不信，我把第一步anaconda创建的siammask环境删掉重新装，解决了23333

**Comment by eathongdoubin** [comment]
好的 那我也试试 哈哈哈哈哈




------------------ 原始邮件 ------------------
发件人: "Hahaemmm"<notifications@github.com>; 
发送时间: 2019年8月12日(星期一) 下午3:43
收件人: "foolwood/SiamMask"<SiamMask@noreply.github.com>; 
抄送: "1254704208"<1254704208@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [foolwood/SiamMask] "bash test_mask_refine.sh config_davis.json"output size question (#86)



 
不好意思啊 我是一个新手 请问具体是什么环境呢😭
  
说出来你可能不信，我把第一步anaconda创建的siammask环境删掉重新装，解决了23333

**Comment by eathongdoubin** [comment]
我试了一下 没搞好 有毒毒
